#ifndef GELEGYSHELLSALEMHUMANDL_H
#define GELEGYSHELLSALEMHUMANDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gElegyShellSalemHumanDL_gElegyShellSalemSleevesTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellSalemTunicTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellSalemGlovesTex_ia16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellSalemHairTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellSalemEyesTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellHumanMouthTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellHumanNostrilsAndSkinTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellHumanBootsTex_rgba16[];
extern u64 gElegyShellSalemHumanDL_gElegyShellHumanPlatformTex_rgba16[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_0[12];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_0[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_1[109];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_1[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_2[24];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_2[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_3[82];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_3[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_4[15];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_4[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_5[45];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_5[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_6[55];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_6[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_7[54];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_7[];
extern Vtx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_vtx_8[23];
extern Gfx gElegyShellSalemHumanDL_gElegyShellSalemHumanDL_mesh_layer_Opaque_tri_8[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemSleeves_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemSleeves_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemTunic_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemTunic_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemGloves_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemGloves_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemHair_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemHair_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemEyes_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemEyes_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemMouth_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemMouth_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemNose_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemNose_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemBoots_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemBoots_layerOpaque[];
extern Gfx mat_gElegyShellSalemHumanDL_ElegySalemPlatform_layerOpaque[];
extern Gfx mat_revert_gElegyShellSalemHumanDL_ElegySalemPlatform_layerOpaque[];
extern Gfx gElegyShellSalemHumanDL[];

#endif
