#ifndef GORONLEFTHANDCLOSEDDL_H
#define GORONLEFTHANDCLOSEDDL_H

#include "ultra64.h"
#include "global.h"

extern u64 GoronLeftHandClosedDL_GoronGlovesTex_i8[];
extern u64 GoronLeftHandClosedDL_GoronHandTex_rgba16[];
extern u64 GoronLeftHandClosedDL_GoronHandThumb_ci8[];
extern u64 GoronLeftHandClosedDL_GoronHandThumb_pal_rgba16[];
extern Vtx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_vtx_0[65];
extern Gfx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_tri_0[];
extern Vtx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_vtx_1[50];
extern Gfx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_tri_1[];
extern Vtx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_vtx_2[18];
extern Gfx GoronLeftHandClosedDL_GoronLeftHandClosedDL_mesh_layer_Opaque_tri_2[];
extern Gfx mat_GoronLeftHandClosedDL_GoronGloves_layerOpaque[];
extern Gfx mat_revert_GoronLeftHandClosedDL_GoronGloves_layerOpaque[];
extern Gfx mat_GoronLeftHandClosedDL_GoronHand_layerOpaque[];
extern Gfx mat_revert_GoronLeftHandClosedDL_GoronHand_layerOpaque[];
extern Gfx mat_GoronLeftHandClosedDL_GoronHandThumb_layerOpaque[];
extern Gfx mat_revert_GoronLeftHandClosedDL_GoronHandThumb_layerOpaque[];
extern Gfx GoronLeftHandClosedDL[];

#endif
