#ifndef GORONRIGHTHANDCLOSEDDL_H
#define GORONRIGHTHANDCLOSEDDL_H

#include "ultra64.h"
#include "global.h"

extern u64 GoronRightHandClosedDL_GoronGlovesTex_i8[];
extern u64 GoronRightHandClosedDL_GoronHandTex_rgba16[];
extern u64 GoronRightHandClosedDL_GoronHandThumb_ci8[];
extern u64 GoronRightHandClosedDL_GoronHandThumb_pal_rgba16[];
extern Vtx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_vtx_0[65];
extern Gfx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_tri_0[];
extern Vtx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_vtx_1[51];
extern Gfx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_tri_1[];
extern Vtx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_vtx_2[17];
extern Gfx GoronRightHandClosedDL_GoronRightHandClosedDL_mesh_layer_Opaque_tri_2[];
extern Gfx mat_GoronRightHandClosedDL_GoronGloves_layerOpaque[];
extern Gfx mat_revert_GoronRightHandClosedDL_GoronGloves_layerOpaque[];
extern Gfx mat_GoronRightHandClosedDL_GoronHand_layerOpaque[];
extern Gfx mat_revert_GoronRightHandClosedDL_GoronHand_layerOpaque[];
extern Gfx mat_GoronRightHandClosedDL_GoronHandThumb_layerOpaque[];
extern Gfx mat_revert_GoronRightHandClosedDL_GoronHandThumb_layerOpaque[];
extern Gfx GoronRightHandClosedDL[];

#endif
