#ifndef GSALEMFIERCEDEITYHAIRSKEL_H
#define GSALEMFIERCEDEITYHAIRSKEL_H

#include "ultra64.h"
#include "global.h"

extern u64 gSalemFierceDeityHairSkel_gSalemFierceDeityHairTex_i8[];
extern Vtx gSalemFierceDeityHairSkel_bone000_gLinkFierceDeityHairRootLimb_mesh_layer_Opaque_vtx_0[156];
extern Gfx gSalemFierceDeityHairSkel_bone000_gLinkFierceDeityHairRootLimb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemFierceDeityHairSkel_bone001_gLinkFierceDeityHairControlLimb_mesh_layer_Opaque_vtx_0[6];
extern Gfx gSalemFierceDeityHairSkel_bone001_gLinkFierceDeityHairControlLimb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemFierceDeityHairSkel_bone002_gLinkFierceDeityHair1Limb_mesh_layer_Opaque_vtx_0[71];
extern Gfx gSalemFierceDeityHairSkel_bone002_gLinkFierceDeityHair1Limb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemFierceDeityHairSkel_bone003_gLinkFierceDeityHair2Limb_mesh_layer_Opaque_vtx_0[59];
extern Gfx gSalemFierceDeityHairSkel_bone003_gLinkFierceDeityHair2Limb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemFierceDeityHairSkel_bone004_gLinkFierceDeityHair3Limb_mesh_layer_Opaque_vtx_0[42];
extern Gfx gSalemFierceDeityHairSkel_bone004_gLinkFierceDeityHair3Limb_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gSalemFierceDeityHairSkel_FDHair_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityHairSkel_FDHair_layerOpaque[];
extern Gfx gSalemFierceDeityHairSkel_bone000_gLinkFierceDeityHairRootLimb_mesh_layer_Opaque[];
extern Gfx gSalemFierceDeityHairSkel_bone001_gLinkFierceDeityHairControlLimb_mesh_layer_Opaque[];
extern Gfx gSalemFierceDeityHairSkel_bone002_gLinkFierceDeityHair1Limb_mesh_layer_Opaque[];
extern Gfx gSalemFierceDeityHairSkel_bone003_gLinkFierceDeityHair2Limb_mesh_layer_Opaque[];
extern Gfx gSalemFierceDeityHairSkel_bone004_gLinkFierceDeityHair3Limb_mesh_layer_Opaque[];
extern FlexSkeletonHeader gSalemFierceDeityHairSkel;
#define GSALEMFIERCEDEITYHAIRSKEL_BONE000_GLINKFIERCEDEITYHAIRROOTLIMB_POS_LIMB 0
#define GSALEMFIERCEDEITYHAIRSKEL_BONE000_GLINKFIERCEDEITYHAIRROOTLIMB_ROT_LIMB 1
#define GSALEMFIERCEDEITYHAIRSKEL_BONE001_GLINKFIERCEDEITYHAIRCONTROLLIMB_LIMB 2
#define GSALEMFIERCEDEITYHAIRSKEL_BONE002_GLINKFIERCEDEITYHAIR1LIMB_LIMB 3
#define GSALEMFIERCEDEITYHAIRSKEL_BONE003_GLINKFIERCEDEITYHAIR2LIMB_LIMB 4
#define GSALEMFIERCEDEITYHAIRSKEL_BONE004_GLINKFIERCEDEITYHAIR3LIMB_LIMB 5
#define GSALEMFIERCEDEITYHAIRSKEL_NUM_LIMBS 6

#endif
