#ifndef GSALEMFIERCEDEITYSCREAMINGMASKDL_H
#define GSALEMFIERCEDEITYSCREAMINGMASKDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gSalemFierceDeityScreamingMaskDL_gLinkFierceDeityEyesDownTex_ci8[];
extern u64 gSalemFierceDeityScreamingMaskDL_gLinkFierceDeityEyesDownTex_pal_rgba16[];
extern u64 gSalemFierceDeityScreamingMaskDL_gLinkFierceDeityMouthOpenTex_ci8[];
extern u64 gSalemFierceDeityScreamingMaskDL_gLinkFierceDeityMouthOpenTex_pal_rgba16[];
extern u64 gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityHairTex_i8[];
extern u64 gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityNoseTex_rgba16[];
extern u64 gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityNose2Tex_rgba16[];
extern u64 gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityHatTex_i8[];
extern u64 gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityMaskScreamPupilsTex_rgba16[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_0[48];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_1[8];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_1[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_2[169];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_2[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_3[4];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_3[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_4[5];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_4[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_5[14];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_5[];
extern Vtx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_vtx_6[6];
extern Gfx gSalemFierceDeityScreamingMaskDL_gSalemFierceDeityScreamingMaskDL_mesh_layer_Opaque_tri_6[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskEyesScream_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskEyesScream_layerOpaque[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskMouth_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskMouth_layerOpaque[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskHair_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskHair_layerOpaque[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskNose_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskNose_layerOpaque[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskNose2_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskNose2_layerOpaque[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskHat_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskHat_layerOpaque[];
extern Gfx mat_gSalemFierceDeityScreamingMaskDL_FDMaskEyesScreamPupils_layerOpaque[];
extern Gfx mat_revert_gSalemFierceDeityScreamingMaskDL_FDMaskEyesScreamPupils_layerOpaque[];
extern Gfx gSalemFierceDeityScreamingMaskDL[];

#endif
