#ifndef GSALEMZORARIGHTFINDL_H
#define GSALEMZORARIGHTFINDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gSalemZoraRightFinDL_gZoraFinTex_ci8[];
extern u64 gSalemZoraRightFinDL_gZoraFinTex_pal_rgba16[];
extern u64 gSalemZoraRightFinDL_gSalemZoraHeadBackTex_rgba16[];
extern u64 gSalemZoraRightFinDL_gSalemZoraFinSkinShadeTex_rgba16[];
extern Vtx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_vtx_0[45];
extern Gfx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_vtx_1[71];
extern Gfx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_tri_1[];
extern Vtx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_vtx_2[45];
extern Gfx gSalemZoraRightFinDL_gSalemZoraRightFinDL_mesh_layer_Opaque_tri_2[];
extern Gfx mat_gSalemZoraRightFinDL_ZoraFin_layerOpaque[];
extern Gfx mat_revert_gSalemZoraRightFinDL_ZoraFin_layerOpaque[];
extern Gfx mat_gSalemZoraRightFinDL_ZoraHeadBack_layerOpaque[];
extern Gfx mat_revert_gSalemZoraRightFinDL_ZoraHeadBack_layerOpaque[];
extern Gfx mat_gSalemZoraRightFinDL_ZoraFinSkinShade_layerOpaque[];
extern Gfx mat_revert_gSalemZoraRightFinDL_ZoraFinSkinShade_layerOpaque[];
extern Gfx gSalemZoraRightFinDL[];

#endif
