#ifndef GSALEMGORONSHIELDINGSKEL_H
#define GSALEMGORONSHIELDINGSKEL_H

#include "ultra64.h"
#include "global.h"

extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_003140_ci8[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_003140_pal_rgba16[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_003A40_ci8[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_003A40_pal_rgba16[];
extern u64 gSalemGoronShieldingSkel_gameplay_keep_Tex_028BB8_i8[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_00CEB8_rgba16[];
extern u64 gSalemGoronShieldingSkel_gSalemGoronHairPurpleTex_rgba16[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_004240_ci8[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_004240_pal_rgba16[];
extern u64 gSalemGoronShieldingSkel_object_link_child_Tex_006200_rgba16[];
extern u64 gSalemGoronShieldingSkel_gSalemGoronSkinTex_rgba16[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_003940_ci8[];
extern u64 gSalemGoronShieldingSkel_object_link_goron_Tex_003940_pal_rgba16[];
extern u64 gSalemGoronShieldingSkel_gSalemGlovesTex_i8[];
extern Vtx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_vtx_0[32];
extern Gfx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_vtx_1[6];
extern Gfx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_tri_1[];
extern Vtx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_vtx_2[6];
extern Gfx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_tri_2[];
extern Vtx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_vtx_3[11];
extern Gfx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_tri_3[];
extern Vtx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_vtx_4[16];
extern Gfx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque_tri_4[];
extern Vtx gSalemGoronShieldingSkel_bone002_gLinkGoronShieldingHeadLimb_mesh_layer_Opaque_vtx_0[32];
extern Gfx gSalemGoronShieldingSkel_bone002_gLinkGoronShieldingHeadLimb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemGoronShieldingSkel_bone002_gLinkGoronShieldingHeadLimb_mesh_layer_Opaque_vtx_1[42];
extern Gfx gSalemGoronShieldingSkel_bone002_gLinkGoronShieldingHeadLimb_mesh_layer_Opaque_tri_1[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_0[18];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_0[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_1[4];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_1[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_2[76];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_2[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_3[36];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_3[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_4[20];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_4[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_5[102];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_5[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_6[48];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_6[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_7[17];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_7[];
extern Vtx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_vtx_8[52];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque_tri_8[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronBack_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronBack_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronTattoo_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronTattoo_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronLeggings_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronLeggings_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronClothingNoCull_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronClothingNoCull_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronClothing_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronClothing_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronHairPurple_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronHairPurple_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronBelly_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronBelly_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronBootTex_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronBootTex_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronSkin_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronSkin_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronHand_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronHand_layerOpaque[];
extern Gfx mat_gSalemGoronShieldingSkel_GoronGloves_layerOpaque[];
extern Gfx mat_revert_gSalemGoronShieldingSkel_GoronGloves_layerOpaque[];
extern Gfx gSalemGoronShieldingSkel_bone001_gLinkGoronShieldingBodyLimb_mesh_layer_Opaque[];
extern Gfx gSalemGoronShieldingSkel_bone002_gLinkGoronShieldingHeadLimb_mesh_layer_Opaque[];
extern Gfx gSalemGoronShieldingSkel_bone003_gLinkGoronShieldingArmsAndLegsLimb_mesh_layer_Opaque[];
extern FlexSkeletonHeader gSalemGoronShieldingSkel;
#define GSALEMGORONSHIELDINGSKEL_BONE000_GLINKGORONSHIELDINGROOTLIMB_POS_LIMB 0
#define GSALEMGORONSHIELDINGSKEL_BONE000_GLINKGORONSHIELDINGROOTLIMB_ROT_LIMB 1
#define GSALEMGORONSHIELDINGSKEL_BONE001_GLINKGORONSHIELDINGBODYLIMB_LIMB 2
#define GSALEMGORONSHIELDINGSKEL_BONE002_GLINKGORONSHIELDINGHEADLIMB_LIMB 3
#define GSALEMGORONSHIELDINGSKEL_BONE003_GLINKGORONSHIELDINGARMSANDLEGSLIMB_LIMB 4
#define GSALEMGORONSHIELDINGSKEL_NUM_LIMBS 5

#endif
